version: 2.1

orbs:
  lacework: lacework/lacework@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@9.0

# Pipeline parameters
parameters:
  # These pipeline parameters are required by the "trigger-integration-tests-workflow"
  # job, by default.
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    type: string
    default: "dev:alpha"

jobs:
  integration-test-install-cli:
    executor: orb-tools/ubuntu
    steps:
      - checkout
      - lacework/install-cli
      - run:
          command: |
            if ! lacework version; then
              echo "The lacework-cli was not found"
              exit 1
            fi

  integration-test-vuln-scan:
    executor: lacework/default
    steps:
      - checkout
      - lacework/vuln-scan-run:
          registry: "index.docker.io"
          repository: "techallylw/lacework-cli"

workflows:
  # This `lint-pack_validate_publish-dev` workflow will run on any commit.
  lint_pack-validate_publish-dev:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      # pack your orb YAML files to a single orb.yml
      # validate the orb.yml file to ensure it is well-formed
      - orb-tools/pack:
          requires:
            - orb-tools/lint

      # release dev version of orb, for testing & possible publishing.
      # orb will be published as dev:alpha and dev:${CIRCLE_SHA1:0:7}.
      # requires a CircleCI API token to be stored as CIRCLE_TOKEN (default)
      # https://circleci.com/docs/2.0/managing-api-tokens
      # store CIRCLE_TOKEN as a project env var or Contexts resource
      # if using Contexts, add your context below
      - orb-tools/publish-dev:
          orb-name: lacework/lacework
          requires:
            - orb-tools/pack

      # trigger an integration workflow to test the
      # dev:${CIRCLE_SHA1:0:7} version of your orb
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          requires:
            - orb-tools/publish-dev

  # This `integration-tests_prod-release` workflow will only run
  # when the run-integration-tests pipeline parameter is set to true.
  # It is meant to be triggered by the "trigger-integration-tests-workflow"
  # job, and run tests on <your orb>@dev:${CIRCLE_SHA1:0:7}.
  integration-tests_prod-release:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - integration-test-install-cli
      - integration-test-vuln-scan

      # publish a semver version of the orb. relies on the commit
      # subject containing the text "[semver:patch|minor|major|skip]"
      # as that will determine whether a patch, minor or major
      # version will be published or if publishing should
      # be skipped.
      # e.g. [semver:patch] will cause a patch version to be published.
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: lacework/lacework

          add-pr-comment: false
          fail-if-semver-not-indicated: true
          publish-version-tag: true
          ssh-fingerprints: x
          requires:
            - integration-test-install-cli
            - integration-test-vuln-scan
          filters:
            branches:
              only: master
